---
# PersistentVolumeClaim for shared data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# ConfigMap for CSV data
apiVersion: v1
kind: ConfigMap
metadata:
  name: produits-scrapy-csv
data:
  produits_scrapy.csv: |
    titre;prix;disponibilite;note_moyenne;description;vendeur;categorie;lien_produit;source_file
    Laptop A;416.99;En stock;4.5;15.6" Laptop with 8GB RAM;Vendor A;Electronics;https://example.com/laptop-a;test_data.csv
    Laptop B;306.99;En stock;3.8;14" Laptop with 4GB RAM;Vendor B;Electronics;https://example.com/laptop-b;test_data.csv
    Laptop C;1178.99;En stock;4.9;17" Gaming Laptop;Vendor C;Electronics;https://example.com/laptop-c;test_data.csv
    Smartphone A;739.99;En stock;4.7;6.5" Smartphone;Vendor D;Electronics;https://example.com/smartphone-a;test_data.csv
    Smartphone B;1311.99;En stock;4.2;6.1" Smartphone;Vendor E;Electronics;https://example.com/smartphone-b;test_data.csv
    Tablet A;581.99;En stock;4.0;10" Tablet;Vendor F;Electronics;https://example.com/tablet-a;test_data.csv
    Tablet B;1033.99;En stock;4.3;12" Tablet;Vendor G;Electronics;https://example.com/tablet-b;test_data.csv
    Monitor A;609.99;En stock;4.6;27" Monitor;Vendor H;Electronics;https://example.com/monitor-a;test_data.csv
    Monitor B;745.99;En stock;4.1;32" Monitor;Vendor I;Electronics;https://example.com/monitor-b;test_data.csv
    Keyboard;129.99;En stock;4.8;Mechanical Keyboard;Vendor J;Electronics;https://example.com/keyboard;test_data.csv
---
# Scraper Job
apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-job
  labels:
    app: scraper
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: oumaimaboughdad/ecommerce_scraper:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ecommerce-data-pvc
      restartPolicy: OnFailure
---
# ML Model Job
apiVersion: batch/v1
kind: Job
metadata:
  name: ml-model-job
  labels:
    app: ml-model
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ecommerce-data-pvc
      - name: csv-data
        configMap:
          name: produits-scrapy-csv
      initContainers:
      - name: init-data
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /data/output
          echo "Copying CSV file to persistent volume..."
          cp /csv-data/produits_scrapy.csv /data/produits_scrapy.csv
          echo "Data initialization complete!"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: csv-data
          mountPath: /csv-data
      containers:
      - name: ml-model
        image: oumaimaboughdad/ecommerce_ml:fixed
        imagePullPolicy: Always
        env:
        - name: INPUT_FILE
          value: "/data/produits_scrapy.csv"
        - name: OUTPUT_DIR
          value: "/data/output"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: OnFailure
---
# Dashboard Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: oumaimaboughdad/ecommerce_llm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ecommerce-data-pvc
---
# Dashboard Service
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  selector:
    app: dashboard
  ports:
  - port: 8501
    targetPort: 8501
  type: NodePort