apiVersion: batch/v1
kind: Job
metadata:
  name: ml-model-job
  labels:
    app: ml-model
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ecommerce-data-pvc
      - name: csv-data
        configMap:
          name: produits-scrapy-csv
      initContainers:
      - name: init-data
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /data/output
          echo "Copying CSV file to persistent volume..."
          cp /csv-data/produits_scrapy.csv /data/produits_scrapy.csv
          echo "Data initialization complete!"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: csv-data
          mountPath: /csv-data
      containers:
      - name: ml-model
        image: oumaimaboughdad/ecommerce_ml:fixed
        imagePullPolicy: Always
        env:
        - name: INPUT_FILE
          value: "/data/produits_scrapy.csv"
        - name: OUTPUT_DIR
          value: "/data/output"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: Never