apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-job
  labels:
    app: scraper
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: oumaimaboughdad/ecommerce_scraper:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ecommerce-data-pvc
      restartPolicy: OnFailure